#ifndef PHOENIX_UTIL_ERROR_H
#define PHOENIX_UTIL_ERROR_H

enum Error {
  // General Codes
  SUCCESS = 0,
  GENERAL_ERROR = 0x01000000,
  WINDOW_ERROR = 0x02000000,
  VULKAN_ERROR = 0x03000000,
  UTIL_ERROR = 0x04000000,
  RENDERER_ERROR = 0x05000000,
  USER_ERROR = 0x06000000,

  // Specific Codes
  // General
  NULL_HANDLE_ERROR = GENERAL_ERROR | 0x01,
  ALLOCATION_ERROR = GENERAL_ERROR | 0x02,
  UNKNOWN_ERROR = GENERAL_ERROR | 0x03,

  // Window
  WINDOW_CREATE_ERROR = WINDOW_ERROR | 0x01,
  WINDOW_START_CONTEXT_ERROR = WINDOW_ERROR | 0x02,
  WINDOW_GET_EXTENSIONS_ERROR = WINDOW_ERROR | 0x03,

  // Vulkan
  VULKAN_INSTANCE_ERROR = VULKAN_ERROR | 0x010000,
  VULKAN_INSTANCE_CREATE_ERROR = VULKAN_INSTANCE_ERROR | 0x01,

  VULKAN_SURFACE_ERROR = VULKAN_ERROR | 0x020000,
  VULKAN_SURFACE_CREATE_ERROR = VULKAN_SURFACE_ERROR | 0x01,

  VULKAN_PHYSICALS_ERROR = VULKAN_ERROR | 0x030000,
  VULKAN_PHYSICALS_ENUMERATE_ERROR = VULKAN_PHYSICALS_ERROR | 0x01,

  VULKAN_DEVICE_ERROR = VULKAN_ERROR | 0x040000,
  VULKAN_DEVICE_NO_GRAPHIC_QUEUE_FAMILY_ERROR = VULKAN_DEVICE_ERROR | 0x01,
  VULKAN_DEVICE_CREATE_ERROR = VULKAN_DEVICE_ERROR | 0x02,
  VULKAN_DEVICE_GET_SURFACE_SUPPORT_ERROR = VULKAN_DEVICE_ERROR | 0x03,
  VULKAN_DEVICE_NO_PRESENT_QUEUE_FAMILY_ERROR = VULKAN_DEVICE_ERROR | 0x04,
  VULKAN_DEVICE_GET_CAPABILITIES_ERROR = VULKAN_DEVICE_ERROR | 0x05,
  VULKAN_DEVICE_GET_FORMATS_ERROR = VULKAN_DEVICE_ERROR | 0x06,
  VULKAN_DEVICE_GET_PRESENT_MODES_ERROR = VULKAN_DEVICE_ERROR | 0x07,
  VULKAN_DEVICE_RELOAD_SURFACE_ERROR = VULKAN_DEVICE_ERROR | 0x08,
  VULKAN_DEVICE_WAIT_IDLE_ERROR = VULKAN_DEVICE_ERROR | 0x09,

  VULKAN_SWAPCHAIN_ERROR = VULKAN_ERROR | 0x050000,
  VULKAN_SWAPCHAIN_CREATE_ERROR = VULKAN_SWAPCHAIN_ERROR | 0x01,
  VULKAN_SWAPCHAIN_ACQUIRE_IMAGE_ERROR = VULKAN_SWAPCHAIN_ERROR | 0x02,
  VULKAN_SWAPCHAIN_OUT_OF_DATE_ERROR = VULKAN_SWAPCHAIN_ERROR | 0x03,
  VULKAN_SWAPCHAIN_FAILED_TO_GET_EXTENT_ERROR = VULKAN_SWAPCHAIN_ERROR | 0x04,

  VULKAN_IMAGES_ERROR = VULKAN_ERROR | 0x060000,
  VULKAN_IMAGES_GET_ERROR = VULKAN_IMAGES_ERROR | 0x01,

  VULKAN_IMAGE_VIEWS_ERROR = VULKAN_ERROR | 0x070000,
  VULKAN_IMAGE_VIEWS_CREATE_ERROR = VULKAN_IMAGE_VIEWS_ERROR | 0x01,

  VULKAN_RENDER_PASS_ERROR = VULKAN_ERROR | 0x080000,
  VULKAN_RENDER_PASS_CREATE_ERROR = VULKAN_RENDER_PASS_ERROR | 0x01,

  VULKAN_SHADER_MODULE_ERROR = VULKAN_ERROR | 0x090000,
  VULKAN_SHADER_MODULE_CREATE_ERROR = VULKAN_SHADER_MODULE_ERROR | 0x01,

  VULKAN_PIPELINE_LAYOUT_ERROR = VULKAN_ERROR | 0x0a0000,
  VULKAN_PIPELINE_LAYOUT_CREATE_ERROR = VULKAN_PIPELINE_LAYOUT_ERROR | 0x01,

  VULKAN_PIPELINE_ERROR = VULKAN_ERROR | 0x0b0000,
  VULKAN_PIPELINE_CREATE_ERROR = VULKAN_PIPELINE_ERROR | 0x01,

  VULKAN_FRAMEBUFFER_ERROR = VULKAN_ERROR | 0x0c0000,
  VULKAN_FRAMEBUFFER_CREATE_ERROR = VULKAN_FRAMEBUFFER_ERROR | 0x01,
  VULKAN_FRAMEBUFFERS_RECREATE_ERROR = VULKAN_FRAMEBUFFER_ERROR | 0x02,

  VULKAN_COMMAND_POOL_ERROR = VULKAN_ERROR | 0x0d0000,
  VULKAN_COMMAND_POOL_CREATE_ERROR = VULKAN_COMMAND_POOL_ERROR | 0x01,

  VULKAN_COMMAND_BUFFER_ERROR = VULKAN_ERROR | 0x0e0000,
  VULKAN_COMMAND_BUFFER_ALLOCATE_ERROR = VULKAN_COMMAND_BUFFER_ERROR | 0x01,
  VULKAN_COMMAND_BUFFER_BEGIN_ERROR = VULKAN_COMMAND_BUFFER_ERROR | 0x02,
  VULKAN_COMMAND_BUFFER_RESET_ERROR = VULKAN_COMMAND_BUFFER_ERROR | 0x03,
  VULKAN_COMMAND_BUFFER_END_ERROR = VULKAN_COMMAND_BUFFER_ERROR | 0x04,

  VULKAN_SEMAPHORE_ERROR = VULKAN_ERROR | 0x0f0000,
  VULKAN_SEMAPHORE_CREATE_ERROR = VULKAN_SEMAPHORE_ERROR | 0x01,

  VULKAN_FENCE_ERROR = VULKAN_ERROR | 0x100000,
  VULKAN_FENCE_CREATE_ERROR = VULKAN_FENCE_ERROR | 0x01,
  VULKAN_FENCES_WAIT_ERROR = VULKAN_FENCE_ERROR | 0x02,
  VULKAN_FENCES_RESET_ERROR = VULKAN_FENCE_ERROR | 0x03,

  VULKAN_QUEUE_ERROR = VULKAN_ERROR | 0x110000,
  VULKAN_QUEUE_SUBMIT_ERROR = VULKAN_QUEUE_ERROR | 0x01,
  VULKAN_QUEUE_PRESENT_ERROR = VULKAN_QUEUE_ERROR | 0x02,
  VULKAN_QUEUE_WAIT_IDLE_ERROR = VULKAN_QUEUE_ERROR | 0x03,

  VULKAN_RAW_BUFFER_ERROR = VULKAN_ERROR | 0x120000,
  VULKAN_RAW_BUFFER_CREATE_ERROR = VULKAN_RAW_BUFFER_ERROR | 0x01,
  VULKAN_RAW_BUFFER_BIND_MEMORY_ERROR = VULKAN_RAW_BUFFER_ERROR | 0x02,

  VULKAN_DEVICE_MEMORY_ERROR = VULKAN_ERROR | 0x130000,
  VULKAN_DEVICE_MEMORY_ALLOCATE_ERROR = VULKAN_DEVICE_MEMORY_ERROR | 0x01,
  VULKAN_DEVICE_MEMORY_FIND_MEMORY_ERROR = VULKAN_DEVICE_MEMORY_ERROR | 0x02,
  VULKAN_DEVICE_MEMORY_MAP_ERROR = VULKAN_DEVICE_MEMORY_ERROR | 0x03,

  VULKAN_BUFFER_ERROR = VULKAN_ERROR | 0x140000,
  VULKAN_BUFFER_CREATE_ERROR = VULKAN_BUFFER_ERROR | 0x01,
  VULKAN_BUFFERS_STAGE_ERROR = VULKAN_BUFFER_ERROR | 0x02,

  VULKAN_DESCRIPTOR_SET_LAYOUT_ERROR = VULKAN_ERROR | 0x150000,
  VULKAN_DESCRIPTOR_SET_LAYOUT_CREATE_ERROR = VULKAN_DESCRIPTOR_SET_LAYOUT_ERROR | 0x01,

  VULKAN_DESCRIPTOR_POOL_ERROR = VULKAN_ERROR | 0x160000,
  VULKAN_DESCRIPTOR_POOL_CREATE_ERROR = VULKAN_DESCRIPTOR_POOL_ERROR | 0x01,

  VULKAN_DESCRIPTOR_SET_ERROR = VULKAN_ERROR | 0x170000,
  VULKAN_DESCRIPTOR_SET_ALLOCATE_ERROR = VULKAN_DESCRIPTOR_SET_ERROR | 0x01,

  // Utils
  FILE_ERROR = UTIL_ERROR | 0x010000,
  FILE_OPEN_ERROR = FILE_ERROR | 0x01,
  FILE_CLOSE_ERROR = FILE_ERROR | 0x02,
  FILE_SEEK_ERROR = FILE_ERROR | 0x03,
  FILE_READ_ERROR = FILE_ERROR | 0x04,
  FILE_INVALID_PERMISSION_ERROR = FILE_ERROR | 0x05,
  FILE_TRUNCATE_ERROR = FILE_ERROR | 0x06,
  FILE_WRITE_ERROR = FILE_ERROR | 0x07,

  RESOURCE_ERROR = UTIL_ERROR | 0x020000,
  RESOURCE_LOAD_ERROR = RESOURCE_ERROR | 0x01,
  RESOURCES_LOAD_ERROR = RESOURCE_ERROR | 0x02,

  // Renderer
  RENDERER_PHYSICALS_CREATE_ERROR = RENDERER_ERROR | 0x01,
  RENDERER_SELECT_PHYSICAL_ERROR = RENDERER_ERROR | 0x02,
  RENDERER_QUEUE_CREATE_ERROR = RENDERER_ERROR | 0x03,
  RENDERER_SELECT_SURFACE_DETAILS_ERROR = RENDERER_ERROR | 0x04,
  RENDERER_IMAGES_CREATE_ERROR = RENDERER_ERROR | 0x05,
  RENDERER_FRAMEBUFFERS_CREATE_ERROR = RENDERER_ERROR | 0x06,
  RENDERER_DRAW_ERROR = RENDERER_ERROR | 0x07,
  RENDERER_CREATE_ERROR = RENDERER_ERROR | 0x08,
  RENDERER_DRAW_CALLBACK_ERROR = RENDERER_ERROR | 0x09,
};
typedef enum Error Error;

#endif
